using UnityEngine;

public class GameManager : MonoBehaviour
{
    [SerializeField] private GameObject[] _sences;
  
    private void Start()
    {
        SenceChange(1);
    }

    void Update()
    {
        
    }

    public void SenceChange(int senceIndex)
    {
        if (senceIndex < 1 || senceIndex > _sences.Length)
        {
            Debug.LogError("Invalid scene index: " + senceIndex);
            return;
        }
        for (int i = 0; i < _sences.Length; i++)
        {
            if (i == senceIndex - 1)
            {
                _sences[i].SetActive(true);
            }
            else
            {
                _sences[i].SetActive(false);
            }
        }
    }

   
    
}